### PR TITLE
travis docker build with clang and new stream path

### PR DESCRIPTION
**Pull request by attugit**

### CODE REVIEW

**Comment by Spawek** [comment]
why do you need 3 versions of g++?

```
+RUN apt-get install -y g++-4.9
+RUN apt-get install -y g++-5
+RUN apt-get install -y g++-6
```

**Comment by attugit** [comment]
i keep just one docker image that has all toolchains.
we had an issue with after upgrade from g++-4.9 to g++-5.
Right now we check on travis build with both gccs.

I also did a check with g++-6 but there is either a compiler issue or we need to patch
source code to fix the build.

In any case the is only one docker image that you need to pull 
to make build.

I was also doing a docker image build "on the fly" but it took a bit longer.
By pushing complete image to docker hub each build on travis needs only about 50s
to pull toolchain

**Comment by Spawek** [comment]
sounds good

**Comment by attugit** [comment]
take a look here:
https://travis-ci.org/attugit/H.265Insight/jobs/139859736

`$ docker build -t testing -f ci/testing.docker . 54.94s`

**Pull request merged**
